package com.andrehofmeister.schoolhouse.feature.student

import com.andrehofmeister.schoolhouse.cdi.ApplicationScopedInjection

@ApplicationScopedInjection
internal annotation class DefaultStudentRepository
